# Generated by Django 4.2.4 on 2023-08-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
