# Generated by Django 4.2.4 on 2023-08-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=60)),
                ('document', models.FileField(upload_to='documents/')),
                ('categories', models.CharField(choices=[('technology', 'Technology'), ('science', 'Science'), ('travel', 'Travel'), ('food', 'Food')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
