# Generated by Django 4.2.4 on 2023-09-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0003_userdetails_content_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='userdetails',
        ),
    ]
